export const actionType = {
    SET_USER: 'SET_USER',
    EDIT_EVENT: 'EDIT_EVENT',
    EDIT_USER: 'EDIT_USER',

    ADD_PARTICIPANT: 'ADD_PARTICIPANT',
    EDIT_PARTICIPANT: 'EDIT_PARTICIPANT',
    ADD_EDIT_PARTICIPANT: 'ADD_EDIT_PARTICIPANT',
    SET_PROFILE: 'SET_PROFILE',
    SET_MODAL_IS_OPEN: 'SET_MODAL_IS_OPEN',
};
